db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_DATABASE: composehub
  volumes:
      - /var/composehub:/var/lib/mysql
web:
  build: .
  command: ./composehub
  ports:
    - "3001:3001"
  links:
    - db:mysql

